version: '2'
services:
  app:
    build: ./src
    restart: always
    depends_on:
      - db
    ports:
      - 9000:9090
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devcamp
    ports:
      - 9001:5432
    volumes:
      - ./db/db-data:/var/lib/postgresql/data