version: '2'
services:
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devcamp
    ports:
      - 9000:5432
    volumes:
      - ./db/db-data:/var/lib/postgresql/data